name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: validation integration
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node js ${{matrix.node_version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}

      - name: Install dependencies
        run: npm install

      - name: App build
        run: npm run build --if-present
      
      - name: Rum test
        run: npm test
        env:
          CI: true